/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemeTestRouteImport } from './routes/theme-test'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyIndexRouteImport } from './routes/study/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MemoryIndexRouteImport } from './routes/memory/index'
import { Route as StudyNewRouteImport } from './routes/study/new'
import { Route as StudySessionIdRouteImport } from './routes/study/$sessionId'
import { Route as SettingsTagsRouteImport } from './routes/settings/tags'
import { Route as PassagePassageIdRouteImport } from './routes/passage/$passageId'
import { Route as MemoryReviewRouteImport } from './routes/memory/review'
import { Route as MemoryPracticeRouteImport } from './routes/memory/practice'
import { Route as MemoryNewRouteImport } from './routes/memory/new'
import { Route as MemoryPackIdRouteImport } from './routes/memory/$packId'
import { Route as MemoryPackIdReviewRouteImport } from './routes/memory_.$packId.review'
import { Route as MemoryPackIdPracticeRouteImport } from './routes/memory_.$packId.practice'

const ThemeTestRoute = ThemeTestRouteImport.update({
  id: '/theme-test',
  path: '/theme-test',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryIndexRoute = MemoryIndexRouteImport.update({
  id: '/memory/',
  path: '/memory/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyNewRoute = StudyNewRouteImport.update({
  id: '/study/new',
  path: '/study/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StudySessionIdRoute = StudySessionIdRouteImport.update({
  id: '/study/$sessionId',
  path: '/study/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTagsRoute = SettingsTagsRouteImport.update({
  id: '/settings/tags',
  path: '/settings/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const PassagePassageIdRoute = PassagePassageIdRouteImport.update({
  id: '/passage/$passageId',
  path: '/passage/$passageId',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryReviewRoute = MemoryReviewRouteImport.update({
  id: '/memory/review',
  path: '/memory/review',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryPracticeRoute = MemoryPracticeRouteImport.update({
  id: '/memory/practice',
  path: '/memory/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryNewRoute = MemoryNewRouteImport.update({
  id: '/memory/new',
  path: '/memory/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryPackIdRoute = MemoryPackIdRouteImport.update({
  id: '/memory/$packId',
  path: '/memory/$packId',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryPackIdReviewRoute = MemoryPackIdReviewRouteImport.update({
  id: '/memory_/$packId/review',
  path: '/memory/$packId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryPackIdPracticeRoute = MemoryPackIdPracticeRouteImport.update({
  id: '/memory_/$packId/practice',
  path: '/memory/$packId/practice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/theme-test': typeof ThemeTestRoute
  '/memory/$packId': typeof MemoryPackIdRoute
  '/memory/new': typeof MemoryNewRoute
  '/memory/practice': typeof MemoryPracticeRoute
  '/memory/review': typeof MemoryReviewRoute
  '/passage/$passageId': typeof PassagePassageIdRoute
  '/settings/tags': typeof SettingsTagsRoute
  '/study/$sessionId': typeof StudySessionIdRoute
  '/study/new': typeof StudyNewRoute
  '/memory/': typeof MemoryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/study/': typeof StudyIndexRoute
  '/memory/$packId/practice': typeof MemoryPackIdPracticeRoute
  '/memory/$packId/review': typeof MemoryPackIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/theme-test': typeof ThemeTestRoute
  '/memory/$packId': typeof MemoryPackIdRoute
  '/memory/new': typeof MemoryNewRoute
  '/memory/practice': typeof MemoryPracticeRoute
  '/memory/review': typeof MemoryReviewRoute
  '/passage/$passageId': typeof PassagePassageIdRoute
  '/settings/tags': typeof SettingsTagsRoute
  '/study/$sessionId': typeof StudySessionIdRoute
  '/study/new': typeof StudyNewRoute
  '/memory': typeof MemoryIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/study': typeof StudyIndexRoute
  '/memory/$packId/practice': typeof MemoryPackIdPracticeRoute
  '/memory/$packId/review': typeof MemoryPackIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/theme-test': typeof ThemeTestRoute
  '/memory/$packId': typeof MemoryPackIdRoute
  '/memory/new': typeof MemoryNewRoute
  '/memory/practice': typeof MemoryPracticeRoute
  '/memory/review': typeof MemoryReviewRoute
  '/passage/$passageId': typeof PassagePassageIdRoute
  '/settings/tags': typeof SettingsTagsRoute
  '/study/$sessionId': typeof StudySessionIdRoute
  '/study/new': typeof StudyNewRoute
  '/memory/': typeof MemoryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/study/': typeof StudyIndexRoute
  '/memory_/$packId/practice': typeof MemoryPackIdPracticeRoute
  '/memory_/$packId/review': typeof MemoryPackIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/theme-test'
    | '/memory/$packId'
    | '/memory/new'
    | '/memory/practice'
    | '/memory/review'
    | '/passage/$passageId'
    | '/settings/tags'
    | '/study/$sessionId'
    | '/study/new'
    | '/memory/'
    | '/settings/'
    | '/study/'
    | '/memory/$packId/practice'
    | '/memory/$packId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/theme-test'
    | '/memory/$packId'
    | '/memory/new'
    | '/memory/practice'
    | '/memory/review'
    | '/passage/$passageId'
    | '/settings/tags'
    | '/study/$sessionId'
    | '/study/new'
    | '/memory'
    | '/settings'
    | '/study'
    | '/memory/$packId/practice'
    | '/memory/$packId/review'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/theme-test'
    | '/memory/$packId'
    | '/memory/new'
    | '/memory/practice'
    | '/memory/review'
    | '/passage/$passageId'
    | '/settings/tags'
    | '/study/$sessionId'
    | '/study/new'
    | '/memory/'
    | '/settings/'
    | '/study/'
    | '/memory_/$packId/practice'
    | '/memory_/$packId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  ThemeTestRoute: typeof ThemeTestRoute
  MemoryPackIdRoute: typeof MemoryPackIdRoute
  MemoryNewRoute: typeof MemoryNewRoute
  MemoryPracticeRoute: typeof MemoryPracticeRoute
  MemoryReviewRoute: typeof MemoryReviewRoute
  PassagePassageIdRoute: typeof PassagePassageIdRoute
  SettingsTagsRoute: typeof SettingsTagsRoute
  StudySessionIdRoute: typeof StudySessionIdRoute
  StudyNewRoute: typeof StudyNewRoute
  MemoryIndexRoute: typeof MemoryIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StudyIndexRoute: typeof StudyIndexRoute
  MemoryPackIdPracticeRoute: typeof MemoryPackIdPracticeRoute
  MemoryPackIdReviewRoute: typeof MemoryPackIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theme-test': {
      id: '/theme-test'
      path: '/theme-test'
      fullPath: '/theme-test'
      preLoaderRoute: typeof ThemeTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/': {
      id: '/memory/'
      path: '/memory'
      fullPath: '/memory/'
      preLoaderRoute: typeof MemoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/new': {
      id: '/study/new'
      path: '/study/new'
      fullPath: '/study/new'
      preLoaderRoute: typeof StudyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$sessionId': {
      id: '/study/$sessionId'
      path: '/study/$sessionId'
      fullPath: '/study/$sessionId'
      preLoaderRoute: typeof StudySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tags': {
      id: '/settings/tags'
      path: '/settings/tags'
      fullPath: '/settings/tags'
      preLoaderRoute: typeof SettingsTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passage/$passageId': {
      id: '/passage/$passageId'
      path: '/passage/$passageId'
      fullPath: '/passage/$passageId'
      preLoaderRoute: typeof PassagePassageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/review': {
      id: '/memory/review'
      path: '/memory/review'
      fullPath: '/memory/review'
      preLoaderRoute: typeof MemoryReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/practice': {
      id: '/memory/practice'
      path: '/memory/practice'
      fullPath: '/memory/practice'
      preLoaderRoute: typeof MemoryPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/new': {
      id: '/memory/new'
      path: '/memory/new'
      fullPath: '/memory/new'
      preLoaderRoute: typeof MemoryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/$packId': {
      id: '/memory/$packId'
      path: '/memory/$packId'
      fullPath: '/memory/$packId'
      preLoaderRoute: typeof MemoryPackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory_/$packId/review': {
      id: '/memory_/$packId/review'
      path: '/memory/$packId/review'
      fullPath: '/memory/$packId/review'
      preLoaderRoute: typeof MemoryPackIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory_/$packId/practice': {
      id: '/memory_/$packId/practice'
      path: '/memory/$packId/practice'
      fullPath: '/memory/$packId/practice'
      preLoaderRoute: typeof MemoryPackIdPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  ThemeTestRoute: ThemeTestRoute,
  MemoryPackIdRoute: MemoryPackIdRoute,
  MemoryNewRoute: MemoryNewRoute,
  MemoryPracticeRoute: MemoryPracticeRoute,
  MemoryReviewRoute: MemoryReviewRoute,
  PassagePassageIdRoute: PassagePassageIdRoute,
  SettingsTagsRoute: SettingsTagsRoute,
  StudySessionIdRoute: StudySessionIdRoute,
  StudyNewRoute: StudyNewRoute,
  MemoryIndexRoute: MemoryIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StudyIndexRoute: StudyIndexRoute,
  MemoryPackIdPracticeRoute: MemoryPackIdPracticeRoute,
  MemoryPackIdReviewRoute: MemoryPackIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
